externalDB:
  enabled: true
  externalDriverType: "postgres"

mysql:
  enabled: false

service:
  type: LoadBalancer

configJSON:
  ServiceSettings:
    EnableCustomEmoji: true

extraEnvVars: []
   - name: POSTGRES_PASSWORD
     valueFrom:
       secretKeyRef:
         # kubectl create secret generic mattermost-postgresql-password --namespace <NAMESPACE> --from-literal postgres-password=<PASSWORD>
         name: mattermost-postgresql-password
         key: postgres-password
   - name: POSTGRES_USER
     value: mattermost@mattermost-k8s-db
   - name: POSTGRES_HOST
     value: mattermost-k8s-db.postgres.database.azure.com
   - name: POSTGRES_PORT
     value: "5432"
   - name: POSTGRES_DB_NAME_MATTERMOST
     value: mattermost
   - name: MM_SQLSETTINGS_DRIVERNAME
     value: "postgres"
   - name: MM_SQLSETTINGS_DATASOURCE
     value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB_NAME_MATTERMOST)?sslmode=disable&connect_timeout=10

