#grafana.ini:
#  server:
#    root_url: https://kyohmizu.japaneast.cloudapp.azure.com/grafana/

#ingress:
#  enabled: true
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/backend-protocol: HTTP
#  labels: {}
#  hosts:
#    - kyohmizu.japaneast.cloudapp.azure.com
#  tls:
#    - secretName: tls-secret
#      hosts:
#        - kyohmizu.japaneast.cloudapp.azure.com
#  path: /grafana(/|$)(.*)

service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
