service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'prometheus'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/prometheus

dashboards:
  default:
    local-dashboard:
      url: https://raw.githubusercontent.com/kyohmizu/mattermost-aks/master/monitoring/dashboards/dashboard-k8s-metrics.json
  prometheus:
    local-dashboard:
      url: https://raw.githubusercontent.com/kyohmizu/mattermost-aks/master/monitoring/dashboards/dashboard-prometheus.json
