apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyohmizu/mattermost-aks.git
    targetRevision: HEAD
    path: cert/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
