externalDB:
  enabled: true
  externalDriverType: "postgres"
  externalConnectionString: "$DATASOURCE_DB"

mysql:
  enabled: false

service:
  type: LoadBalancer

configJSON:
  ServiceSettings:
    EnableCustomEmoji: true
