{
 "title": "Prometheus",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"}",
     "legendFormat": "node={{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes / on (kubernetes_node) node_memory_MemTotal_bytes",
     "legendFormat": "node={{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "CPU Usage By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - avg by(kubernetes_node)(irate(node_cpu_seconds_total{mode='idle'}[5m])))",
     "legendFormat": "node={{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "kube-system Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"kube-system\"}) by(pod_name)",
     "legendFormat": "pod={{pod_name}}"
    }
   ]
  },
  {
   "title": "default-ns Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"default\"}) by(pod_name)",
     "legendFormat": "pod={{pod_name}}"
    }
   ]
  }
 ]
}